---
title: "Contingency tables and Cramer's V"
format: 
  html:
    self-contained: true
    table-of-contents: true
    number-sections: true
    df-print: kable
editor: visual
execute: 
  eval: true
  warning: false
  message: false
---


```{r setup, echo = FALSE}
JuliaCall::julia_setup(JULIA_HOME = "/Applications/Julia-1.9.app/Contents/Resources/julia/bin/")
knitr::opts_chunk$set(engine.path = list(
  python = "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10",
  julia = "/Applications/Julia-1.9.app/Contents/Resources/julia/bin/"
))
```

## Setup

::: panel-tabset
## R

Install `vcd` packages if necessary.

```{r, eval = FALSE}
install.packages("vcd")
```

```{r}
library(vcd)
```

Read in the dataset for the lecture. 

```{r}
df <- read.csv("../data/polish-jvs.csv", colClasses = c(rep("character", 6), "numeric"))
head(df)
```


## Python

Load modules

```{bash, eval = F}
!pip install pingouin 
```

```{python}
import numpy as np
import scipy.stats as st
import pingouin as pg
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.mosaicplot import mosaic
```

```{python}
df = pd.read_csv("../data/polish-jvs.csv", dtype={"id": np.int64, "woj":str, "public":str,"size": str, "nace_division": str, "nace": str})
df.head()
```

## Julia

Install modules

```{julia, eval = F}
using Pkg
Pkg.add(["HypothesisTests", "StatsBase", "CSV", "FreqTables"])
```

Load packages

```{julia}
using Random
using Distributions
using HypothesisTests
using StatsBase
using DataFrames
using CSV
using FreqTables
```


```{julia}
df=CSV.read("../data/polish-jvs.csv", DataFrame, 
            types = Dict(:id => Int64, :woj=> String, :public=> String, 
                         :size => String, :nace_division => String, :nace => String));
first(df, 5)
```

:::


## Contingency tables -- $\chi^2$ test and Cramer's V correlation coefficient

Is there an association between size, and having at least one vacancy? If yes, what is the size of this effect (i.e. correlation)?

::: panel-tabset
## R

```{r}
df$vac <- df$vacancies > 0
tab1 <- with(df, table(size, vac))
prop.table(tab1, margin=1)
prop.table(tab1, margin=2)
mosaicplot(tab1)
chisq.test(tab1)
```
```{r}
assocstats(tab1)
```
```{r}
xtabs(~size+vac, df) |> summary()
```

## Python

```{python}
df["vac"] = np.where(df["vacancies"] > 0, True, False)
mosaic(df, ['size', 'vac'])
plt.show()
tab1 = st.contingency.crosstab(df["size"], df["vac"])
res1=st.chi2_contingency(tab1.count)
[res1.statistic, np.sqrt(res1.statistic/np.sum(tab1.count))]
pg.chi2_independence(df, x = "size", y = "vac")
```
## Julia

```{julia}
df.vac = ifelse.(df.vacancies .> 0, true, false);
tab1=freqtable(df, :size, :vac)
res1=ChisqTest(tab1)
sqrt(res1.stat / sum(tab1))
```

:::
